---
- name: Install Nginx
  package:
    name: nginx
    state: present
  notify:
    - restart nginx

# - name: Make nginx cache directory
#   file:
#     path: /var/lib/nginx/cache
#     state: directory
#     owner: nginx
#     group: nginx
#     mode: 700
#   notify:
#     - restart nginx

# - name: Make SSL directory
#   file:
#     path: /etc/nginx/ssl
#     state: directory
#     owner: nginx
#     group: nginx
#     mode: 700
#   notify:
#     - restart nginx
