name: LEMP_CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Setup Virtual Environment
      run: sudo apt install virtualenv -y
    - name: Install Dependencies
      run: |
        virtualenv .env 
        source .env/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Molecule Tests
      run: |
        source .env/bin/activate
        molecule test --destroy=never